## Hello Neuron!

This is our first dive into neural nets and its applications to NLP. 

**Disclaimer:** This tutorial will assume that you have some basic knowledge of Python, linear algebra and the `numpy` library.


In [1]:
import numpy as np

## Sigmoid / Logistic Function

A sigmoid/logistic function squeezes a real number value to a space between 0 to 1 exclusively at the extremes (0.0, 1.0) , i.e. never touching 0 or 1.

<img src="images/logistic-curve.png">

In [2]:
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

## Let's create a random 1-Dimension array (aka. a vector)

In [3]:
random_array = np.random.rand(3)
random_array

array([ 0.14814525,  0.69084814,  0.0935779 ])

In [4]:
sigmoid(random_array) 

array([ 0.53696872,  0.66615557,  0.52337742])

In [5]:
random_minus6_to_plus6_array = np.random.uniform(-6, 6, size=3)
random_minus6_to_plus6_array

array([-4.4093679 , -2.52597941, -0.96298555])

In [6]:
sigmoid(random_minus6_to_plus6_array)

array([ 0.01201671,  0.07405688,  0.27628084])

## If the x-values of the array falls below -6, we see that the sigmoid(x) -> 0

In [7]:
sigmoid(np.random.uniform(-100, -6, size=3))

array([  7.36555086e-40,   2.08745062e-39,   4.62762848e-25])

## If the x-values of the array goes above +6, we see that the sigmoid(x) -> 1

In [8]:
sigmoid(np.random.uniform(6, 100, size=3))

array([ 1.        ,  1.        ,  0.99999875])

## Logistic Regression

Now that we have seen how a logistic/sigmoid function "squeeze" the input vector and output

## The Zoo of Activation Functions

The sigmoid and softmax are usually called *activation functions* in neural net terminology, they act as sort of a data "squasher" usually between hidden layers and before the final output layer.

In [ ]:
# IPython jibber-jabber...
from IPython.display import Image # Image(filename='something.png')